services:
  
  metabase-db:
    image: postgres:13.1-alpine
    container_name: metabase-db
    restart: always
    environment:
      POSTGRES_USER: mbuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metabase
    networks:
      - dokploy-network
  
  metabase:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "5432"
      MB_DB_USER: "mbuser"
      MB_DB_PASS: "password"
      MB_DB_HOST: "metabase-db"
      JAVA_TIMEZONE: "America/Maceio"
    networks:
      - dokploy-network
    depends_on:
      - metabase-db

volumes:
  rabbitmq_data:
  redis_data:

networks:
  dokploy-network:
    external: true        